Repository AnsimCar/asc-spring-server, pull requests merged in 2023-04, with the labels that each got.

#7 회원가입 입력데이터 검증 및 예외 처리
  build.gradle
  src/main/java/project/asc/AnsimCar/controller/AccountController.java
  src/main/java/project/asc/AnsimCar/controller/ExceptionController.java
  src/main/java/project/asc/AnsimCar/dto/account/AccountDto.java
  src/main/java/project/asc/AnsimCar/dto/account/AccountRequest.java
  src/main/java/project/asc/AnsimCar/exception/EmailExistException.java
  src/main/java/project/asc/AnsimCar/service/AccountService.java
  src/main/resources/templates/account/register.html
  src/main/resources/templates/layout/header.html
  src/test/java/project/asc/AnsimCar/common/annotation/ServiceTest.java
  src/test/java/project/asc/AnsimCar/service/AccountServiceTest.java
Labels: 🔥 백엔드, 🌈 프론트

#11 자동차 엔티티
  src/main/java/project/asc/AnsimCar/domain/UserCar.java
  src/main/java/project/asc/AnsimCar/domain/type/CarCategory.java
  src/main/java/project/asc/AnsimCar/domain/type/Fuel.java
  src/main/java/project/asc/AnsimCar/domain/type/Transmission.java
Labels: 🔥 백엔드

#13 테이블 공통 컬럼
  src/main/java/project/asc/AnsimCar/config/JpaConfig.java
  src/main/java/project/asc/AnsimCar/domain/Account.java
  src/main/java/project/asc/AnsimCar/domain/UserCar.java
  src/main/java/project/asc/AnsimCar/domain/common/BaseEntity.java
Labels: 🔥 백엔드

#18 #16 - 차량 테스트 코드 및 리팩토링
  src/main/java/project/asc/AnsimCar/controller/ExceptionController.java
  src/main/java/project/asc/AnsimCar/domain/UserCar.java
  src/main/java/project/asc/AnsimCar/dto/usercar/UserCarRequest.java
  src/main/java/project/asc/AnsimCar/dto/usercar/request/UserCarCreateRequest.java
  src/main/java/project/asc/AnsimCar/dto/usercar/request/UserCarUpdateRequest.java
  src/main/java/project/asc/AnsimCar/dto/usercar/response/UserCarResponse.java
  src/main/java/project/asc/AnsimCar/exception/Account/AccountException.java
  src/main/java/project/asc/AnsimCar/exception/Account/AccountNotFoundException.java
  src/main/java/project/asc/AnsimCar/exception/Account/EmailExistException.java
  src/main/java/project/asc/AnsimCar/exception/UserCar/UserCarException.java
  src/main/java/project/asc/AnsimCar/exception/UserCar/UserCarNotFoundException.java
  src/main/java/project/asc/AnsimCar/exception/UserCar/UserCarOwnerException.java
  src/main/java/project/asc/AnsimCar/repository/UserCarRepository.java
  src/main/java/project/asc/AnsimCar/service/AccountService.java
  src/main/java/project/asc/AnsimCar/service/UserCarService.java
  src/test/java/project/asc/AnsimCar/common/fixture/UserCarFixture.java
  src/test/java/project/asc/AnsimCar/repository/UserCarRepositoryTest.java
  src/test/java/project/asc/AnsimCar/service/AccountServiceTest.java
  src/test/java/project/asc/AnsimCar/service/UserCarServiceTest.java
Labels: 🔥 백엔드, ⚒ 리팩토링

#19 리팩토링
  src/main/java/project/asc/AnsimCar/controller/AccountController.java
  src/main/java/project/asc/AnsimCar/controller/ExceptionController.java
  src/main/java/project/asc/AnsimCar/domain/Account.java
  src/main/java/project/asc/AnsimCar/domain/UserCar.java
  src/main/java/project/asc/AnsimCar/dto/account/AccountRequest.java
  src/main/java/project/asc/AnsimCar/dto/account/request/AccountCreateRequest.java
  src/main/java/project/asc/AnsimCar/dto/account/response/AccountResponse.java
  src/main/java/project/asc/AnsimCar/dto/usercar/response/UserCarResponse.java
  src/main/java/project/asc/AnsimCar/service/AccountService.java
  src/main/java/project/asc/AnsimCar/service/UserCarService.java
  src/test/java/project/asc/AnsimCar/common/fixture/AccountFixture.java
  src/test/java/project/asc/AnsimCar/common/fixture/UserCarFixture.java
  src/test/java/project/asc/AnsimCar/repository/UserCarRepositoryTest.java
  src/test/java/project/asc/AnsimCar/service/AccountServiceTest.java
  src/test/java/project/asc/AnsimCar/service/UserCarServiceTest.java
Labels: ⚒ 리팩토링

#21 차량 렌트 도메인 및 dto
  src/main/java/project/asc/AnsimCar/domain/Address.java
  src/main/java/project/asc/AnsimCar/domain/AfterImage.java
  src/main/java/project/asc/AnsimCar/domain/BeforeImage.java
  src/main/java/project/asc/AnsimCar/domain/Rent.java
  src/main/java/project/asc/AnsimCar/domain/type/Status.java
  src/main/java/project/asc/AnsimCar/dto/address/request/AddressCreateRequest.java
  src/main/java/project/asc/AnsimCar/dto/address/response/AddressResponse.java
  src/main/java/project/asc/AnsimCar/dto/before/request/BeforeImageCreateRequest.java
  src/main/java/project/asc/AnsimCar/dto/before/response/BeforeImageResponse.java
  src/main/java/project/asc/AnsimCar/dto/image/after/request/AfterImageCreateRequest.java
  src/main/java/project/asc/AnsimCar/dto/image/after/response/AfterImageResponse.java
  src/main/java/project/asc/AnsimCar/dto/rent/request/RentCreateRequest.java
  src/main/java/project/asc/AnsimCar/dto/rent/request/RentUpdateRequest.java
  src/main/java/project/asc/AnsimCar/dto/rent/response/RentResponse.java
  src/main/java/project/asc/AnsimCar/service/UserCarService.java
Labels: 🔥 백엔드

#25 차량 렌트 CRUD
  src/main/java/project/asc/AnsimCar/domain/Address.java
  src/main/java/project/asc/AnsimCar/domain/Rent.java
  src/main/java/project/asc/AnsimCar/dto/address/request/AddressCreateRequest.java
  src/main/java/project/asc/AnsimCar/dto/rent/request/RentCreateRequest.java
  src/main/java/project/asc/AnsimCar/dto/rent/response/RentResponse.java
  src/main/java/project/asc/AnsimCar/exception/rent/RentException.java
  src/main/java/project/asc/AnsimCar/exception/rent/RentNotFoundException.java
  src/main/java/project/asc/AnsimCar/exception/rent/RentOwnerException.java
  src/main/java/project/asc/AnsimCar/repository/AddressRepository.java
  src/main/java/project/asc/AnsimCar/repository/RentRepository.java
  src/main/java/project/asc/AnsimCar/repository/UserCarRepository.java
  src/main/java/project/asc/AnsimCar/service/RentService.java
  src/main/java/project/asc/AnsimCar/service/UserCarService.java
  src/test/java/project/asc/AnsimCar/common/fixture/AddressFixture.java
  src/test/java/project/asc/AnsimCar/common/fixture/RentFixture.java
  src/test/java/project/asc/AnsimCar/common/fixture/UserCarFixture.java
  src/test/java/project/asc/AnsimCar/repository/RentRepositoryTest.java
  src/test/java/project/asc/AnsimCar/repository/UserCarRepositoryTest.java
  src/test/java/project/asc/AnsimCar/service/RentServiceTest.java
  src/test/java/project/asc/AnsimCar/service/UserCarServiceTest.java
Labels: 🔥 백엔드

#27 차량 리뷰 도메인 및 dto
  src/main/java/project/asc/AnsimCar/domain/Account.java
  src/main/java/project/asc/AnsimCar/domain/Review.java
  src/main/java/project/asc/AnsimCar/domain/UserCar.java
  src/main/java/project/asc/AnsimCar/dto/review/request/ReviewCreateRequest.java
  src/main/java/project/asc/AnsimCar/dto/review/request/ReviewUpdateRequest.java
  src/main/java/project/asc/AnsimCar/dto/review/response/ReviewResponse.java
Labels: 🔥 백엔드

#29 차량 리뷰 CRUD 및 테스트 코드
  src/main/java/project/asc/AnsimCar/repository/ReviewRepository.java
  src/test/java/project/asc/AnsimCar/common/fixture/ReviewFixture.java
  src/test/java/project/asc/AnsimCar/repository/ReviewRepositoryTest.java
Labels: 🔥 백엔드

#39 입력데이터검증
  src/main/java/project/asc/AnsimCar/controller/AccountController.java
  src/main/java/project/asc/AnsimCar/controller/UserCarController.java
  src/main/java/project/asc/AnsimCar/dto/usercar/request/UserCarCreateRequest.java
  src/main/resources/templates/account/info.html
  src/main/resources/templates/account/update.html
  src/main/resources/templates/usercar/addUserCar.html
  src/main/resources/templates/usercar/info.html
  src/main/resources/templates/usercar/list.html
Labels: 🔥 백엔드, 🌈 프론트

#42 AWS S3 초기 설정
  build.gradle
  src/main/java/project/asc/AnsimCar/aws/s3/S3Config.java
  src/main/java/project/asc/AnsimCar/aws/s3/S3Uploader.java
  src/main/java/project/asc/AnsimCar/controller/UserCarController.java
  src/main/java/project/asc/AnsimCar/domain/type/CarCategory.java
  src/main/resources/application.yml
Labels: 🔥 백엔드, ⚙세팅

#46 렌트 컨트롤러 및 뷰
  .gitignore
  build.gradle
  src/main/java/project/asc/AnsimCar/controller/ExceptionController.java
  src/main/java/project/asc/AnsimCar/controller/RentController.java
  src/main/java/project/asc/AnsimCar/dto/rent/request/RentCreateRequest.java
  src/main/java/project/asc/AnsimCar/dto/rent/request/RentSearchRequest.java
  src/main/java/project/asc/AnsimCar/dto/rent/response/RentItemDetailResponse.java
  src/main/java/project/asc/AnsimCar/exception/rent/RentExistException.java
  src/main/java/project/asc/AnsimCar/repository/RentRepository.java
  src/main/java/project/asc/AnsimCar/repository/querydsl/QueryDslConfig.java
  src/main/java/project/asc/AnsimCar/repository/querydsl/rent/RentRepositoryCustom.java
  src/main/java/project/asc/AnsimCar/repository/querydsl/rent/RentRepositoryCustomImpl.java
  src/main/java/project/asc/AnsimCar/service/RentService.java
  src/main/resources/application.yml
  src/main/resources/templates/layout/mypageTop.html
  src/main/resources/templates/layout/rentTop.html
  src/main/resources/templates/layout/top.html
  src/main/resources/templates/rent/addRent.html
  src/main/resources/templates/rent/list.html
  src/main/resources/templates/usercar/list.html
  src/test/java/project/asc/AnsimCar/common/fixture/RentFixture.java
  src/test/java/project/asc/AnsimCar/service/RentServiceTest.java
Labels: 🔥 백엔드, 🌈 프론트

#48 #47 - cascade 적용
  src/main/java/project/asc/AnsimCar/domain/Account.java
  src/main/java/project/asc/AnsimCar/domain/Rent.java
  src/main/java/project/asc/AnsimCar/domain/UserCar.java
  src/main/java/project/asc/AnsimCar/domain/type/Status.java
  src/main/java/project/asc/AnsimCar/service/UserCarService.java
Labels: 🐞 버그, 🛠수정

#51 렌트 대여 기록 및 약간의 리팩토링
  src/main/java/project/asc/AnsimCar/aws/s3/S3Config.java
  src/main/java/project/asc/AnsimCar/aws/s3/S3Upload.java
  src/main/java/project/asc/AnsimCar/controller/RentController.java
  src/main/java/project/asc/AnsimCar/domain/Account.java
  src/main/java/project/asc/AnsimCar/domain/Rent.java
  src/main/java/project/asc/AnsimCar/dto/account/request/AccountCreateRequest.java
  src/main/java/project/asc/AnsimCar/dto/account/request/AccountUpdateRequest.java
  src/main/java/project/asc/AnsimCar/dto/account/response/AccountResponse.java
  src/main/java/project/asc/AnsimCar/dto/rent/response/RentItemDetailResponse.java
  src/main/java/project/asc/AnsimCar/dto/rent/response/RentResponse.java
  src/main/java/project/asc/AnsimCar/repository/RentRepository.java
  src/main/java/project/asc/AnsimCar/service/RentService.java
  src/main/resources/templates/account/register.html
  src/main/resources/templates/account/update.html
  src/main/resources/templates/rent/addRent.html
  src/main/resources/templates/rent/detail.html
  src/main/resources/templates/rent/info.html
  src/main/resources/templates/rent/list.html
  src/main/resources/templates/rent/rentHistory.html
Labels: 🔥 백엔드, ⚒ 리팩토링, 🌈 프론트, ⚙세팅, 🛠수정

#53 렌트 등록 기록
  src/main/java/project/asc/AnsimCar/controller/RentController.java
  src/main/java/project/asc/AnsimCar/domain/Rent.java
  src/main/java/project/asc/AnsimCar/dto/image/before/request/BeforeImageCreateRequest.java
  src/main/java/project/asc/AnsimCar/dto/rent/response/RentResponse.java
  src/main/java/project/asc/AnsimCar/exception/usercar/UserCarRentOwnerException.java
  src/main/java/project/asc/AnsimCar/repository/RentRepository.java
  src/main/java/project/asc/AnsimCar/service/RentService.java
  src/main/resources/templates/rent/addHistory.html
  src/main/resources/templates/rent/addHistoryDetail.html
  src/main/resources/templates/rent/photo.html
  src/test/java/project/asc/AnsimCar/repository/RentRepositoryTest.java
  src/test/java/project/asc/AnsimCar/service/RentServiceTest.java
Labels: 🔥 백엔드, 🌈 프론트
